import { Injectable } from "@angular/core";

@Injectable({
  providedIn: "root",
})
export class MenuItems {
  menuItems: any;
  constructor() {
    this.menuItems = JSON.parse(localStorage.getItem("menuData"));

    if (this.menuItems == null) {
      this.menuItems = [
        {
          menuid: 1,
          name: "Masters",
          dispName: "Masters",
          classid: null,
          parentid: null,
          level: 0,
          aclid: null,
        },
        {
          menuid: 2,
          name: "Country",
          dispName: "Country",
          classid: 1,
          parentid: 1,
          level: 1,
          aclid: null,
        },
        {
          menuid: 3,
          name: "State",
          dispName: "State",
          classid: 2,
          parentid: 1,
          level: 1,
          aclid: null,
        },
        {
          menuid: 4,
          name: "City",
          dispName: "City",
          classid: 3,
          parentid: 1,
          level: 1,
          aclid: null,
        },
        {
          menuid: 5,
          name: "Pincode",
          dispName: "Pincode",
          classid: 4,
          parentid: 1,
          level: 1,
          aclid: null,
        },
        {
          menuid: 6,
          name: "Area",
          dispName: "Area",
          classid: 5,
          parentid: 1,
          level: 1,
          aclid: null,
        },
        {
          menuid: 7,
          name: "Service Area",
          dispName: "Service Area",
          classid: 6,
          parentid: 1,
          level: 1,
          aclid: null,
        },
        {
          menuid: 8,
          name: "Customer",
          dispName: "Customer",
          classid: null,
          parentid: null,
          level: 0,
          aclid: null,
        },
        {
          menuid: 9,
          name: "Postpaid Customer",
          dispName: "Postpaid Customer",
          classid: 7,
          parentid: 8,
          level: 1,
          aclid: null,
        },
        {
          menuid: 10,
          name: "Prepaid Customer",
          dispName: "Prepaid Customer",
          classid: 7,
          parentid: 8,
          level: 1,
          aclid: null,
        },
        {
          menuid: 11,
          name: "Customer CAF",
          dispName: "Customer CAF",
          classid: 7,
          parentid: 8,
          level: 1,
          aclid: null,
        },
        {
          menuid: 12,
          name: "Partner Management",
          dispName: "Partner Management",
          classid: null,
          parentid: null,
          level: 0,
          aclid: null,
        },
        {
          menuid: 13,
          name: "Partner",
          dispName: "Partner",
          classid: 8,
          parentid: 12,
          level: 1,
          aclid: null,
        },
        {
          menuid: 14,
          name: "Product",
          dispName: "Product",
          classid: null,
          parentid: null,
          level: 0,
          aclid: null,
        },
        {
          menuid: 15,
          name: "Service",
          dispName: "Service",
          classid: 9,
          parentid: 14,
          level: 1,
          aclid: null,
        },
        {
          menuid: 16,
          name: "Tax",
          dispName: "Tax",
          classid: 10,
          parentid: 14,
          level: 1,
          aclid: null,
        },
        {
          menuid: 17,
          name: "Charge",
          dispName: "Charge",
          classid: 11,
          parentid: 14,
          level: 1,
          aclid: null,
        },
        {
          menuid: 18,
          name: "Discount",
          dispName: "Discount",
          classid: 12,
          parentid: 14,
          level: 1,
          aclid: null,
        },
        {
          menuid: 19,
          name: "Qos Policy",
          dispName: "Qos Policy",
          classid: 13,
          parentid: 14,
          level: 1,
          aclid: null,
        },
        {
          menuid: 20,
          name: "Plan",
          dispName: "Plan",
          classid: 14,
          parentid: 14,
          level: 1,
          aclid: null,
        },
        {
          menuid: 21,
          name: "Plan Bundle",
          dispName: "Plan Bundle",
          classid: 15,
          parentid: 12,
          level: 1,
          aclid: null,
        },
        {
          menuid: 22,
          name: "Billing",
          dispName: "Billing",
          classid: null,
          parentid: null,
          level: 0,
          aclid: null,
        },
        {
          menuid: 23,
          name: "Bill Template",
          dispName: "Bill Template",
          classid: 16,
          parentid: 22,
          level: 1,
          aclid: null,
        },
        {
          menuid: 24,
          name: "Bill Run",
          dispName: "Bill Run",
          classid: null,
          parentid: 22,
          level: 1,
          aclid: null,
        },
        {
          menuid: 25,
          name: "Bill Run Master",
          dispName: "Bill Run Master",
          classid: 17,
          parentid: 111,
          level: 2,
          aclid: null,
        },
        {
          menuid: 26,
          name: "Invoice Master",
          dispName: "Invoice Master",
          classid: 18,
          parentid: 111,
          level: 2,
          aclid: null,
        },
        {
          menuid: 27,
          name: "Trial Bill Run",
          dispName: "Trial Bill Run",
          classid: null,
          parentid: 22,
          level: 1,
          aclid: null,
        },
        {
          menuid: 28,
          name: "Trial Bill Run Master",
          dispName: "Trial Bill Run Master",
          classid: 19,
          parentid: 116,
          level: 2,
          aclid: null,
        },
        {
          menuid: 29,
          name: "Trial Invoice Master",
          dispName: "Trial Invoice Master",
          classid: 20,
          parentid: 116,
          level: 2,
          aclid: null,
        },
        {
          menuid: 30,
          name: "Payment System",
          dispName: "Payment System",
          classid: null,
          parentid: null,
          level: 0,
          aclid: null,
        },
        {
          menuid: 31,
          name: "Record Payment",
          dispName: "Record Payment",
          classid: 21,
          parentid: 30,
          level: 1,
          aclid: null,
        },
        {
          menuid: 32,
          name: "Search Payment",
          dispName: "Search Payment",
          classid: 21,
          parentid: 30,
          level: 1,
          aclid: null,
        },
        {
          menuid: 33,
          name: "Ticketing System",
          dispName: "Ticketing System",
          classid: null,
          parentid: null,
          level: 0,
          aclid: null,
        },
        {
          menuid: 34,
          name: "Resolution Master",
          dispName: "Resolution Master",
          classid: 22,
          parentid: 33,
          level: 1,
          aclid: null,
        },
        {
          menuid: 36,
          name: "Ticket",
          dispName: "Ticket",
          classid: 24,
          parentid: 33,
          level: 1,
          aclid: null,
        },
        {
          menuid: 37,
          name: "Dunning",
          dispName: "Dunning",
          classid: null,
          parentid: null,
          level: 0,
          aclid: null,
        },
        {
          menuid: 39,
          name: "Notification",
          dispName: "Notification",
          classid: null,
          parentid: null,
          level: 0,
          aclid: null,
        },
        {
          menuid: 40,
          name: "Template",
          dispName: "Template",
          classid: null,
          parentid: null,
          level: 0,
          aclid: null,
        },
        {
          menuid: 41,
          name: "Email Configuration",
          dispName: "Email Configuration",
          classid: 27,
          parentid: 39,
          level: 1,
          aclid: null,
        },
        {
          menuid: 42,
          name: "SMS Configuration",
          dispName: "SMS Configuration",
          classid: 28,
          parentid: 39,
          level: 1,
          aclid: null,
        },
        {
          menuid: 43,
          name: "Email",
          dispName: "Email",
          classid: 75,
          parentid: 39,
          level: 1,
          aclid: null,
        },
        {
          menuid: 44,
          name: "SMS",
          dispName: "SMS",
          classid: 76,
          parentid: 39,
          level: 1,
          aclid: null,
        },
        {
          menuid: 45,
          name: "Network",
          dispName: "Network",
          classid: null,
          parentid: null,
          level: 0,
          aclid: null,
        },
        {
          menuid: 46,
          name: "Network Device",
          dispName: "Network Device",
          classid: 29,
          parentid: 45,
          level: 1,
          aclid: null,
        },
        {
          menuid: 47,
          name: "MVNO",
          dispName: "MVNO",
          classid: 30,
          parentid: null,
          level: 0,
          aclid: null,
        },
        {
          menuid: 48,
          name: "AAA",
          dispName: "AAA",
          classid: null,
          parentid: null,
          level: 0,
          aclid: null,
        },
        {
          menuid: 49,
          name: "Radius Group",
          dispName: "Radius Group",
          classid: 38,
          parentid: 48,
          level: 1,
          aclid: null,
        },
        {
          menuid: 50,
          name: "Radius Client",
          dispName: "Radius Client",
          classid: 37,
          parentid: 48,
          level: 1,
          aclid: null,
        },
        {
          menuid: 51,
          name: "Radius Customer",
          dispName: "Radius Customer",
          classid: 77,
          parentid: 48,
          level: 1,
          aclid: null,
        },
        {
          menuid: 52,
          name: "CDRs",
          dispName: "CDRs",
          classid: 39,
          parentid: 48,
          level: 1,
          aclid: null,
        },
        {
          menuid: 53,
          name: "Live Users",
          dispName: "Live Users",
          classid: 40,
          parentid: 48,
          level: 1,
          aclid: null,
        },
        {
          menuid: 54,
          name: "Proxy Configuration",
          dispName: "Proxy Configuration",
          classid: 78,
          parentid: 48,
          level: 1,
          aclid: null,
        },
        {
          menuid: 55,
          name: "Dictionary",
          dispName: "Dictionary",
          classid: 41,
          parentid: 48,
          level: 1,
          aclid: null,
        },
        {
          menuid: 56,
          name: "Authentication Audit",
          dispName: "Authentication Audit",
          classid: 42,
          parentid: 48,
          level: 1,
          aclid: null,
        },
        {
          menuid: 57,
          name: "CoA/DM Profile",
          dispName: "CoA/DM Profile",
          classid: 43,
          parentid: 48,
          level: 1,
          aclid: null,
        },
        {
          menuid: 58,
          name: "Radius Profile",
          dispName: "Radius Profile",
          classid: 31,
          parentid: 48,
          level: 1,
          aclid: null,
        },
        {
          menuid: 59,
          name: "Device Management",
          dispName: "Device Management",
          classid: 79,
          parentid: 48,
          level: 1,
          aclid: null,
        },
        {
          menuid: 60,
          name: "DB Mapping Master",
          dispName: "DB Mapping Master",
          classid: 44,
          parentid: 48,
          level: 1,
          aclid: null,
        },
        {
          menuid: 61,
          name: "Template Management",
          dispName: "Template Management",
          classid: null,
          parentid: 48,
          level: 1,
          aclid: null,
        },
        {
          menuid: 62,
          name: "Audit",
          dispName: "Audit",
          classid: null,
          parentid: null,
          level: 0,
          aclid: null,
        },
        {
          menuid: 63,
          name: "Audit Log",
          dispName: "Audit Log",
          classid: 32,
          parentid: 62,
          level: 1,
          aclid: null,
        },
        {
          menuid: 64,
          name: "Settings",
          dispName: "Settings",
          classid: null,
          parentid: null,
          level: 0,
          aclid: null,
        },
        {
          menuid: 65,
          name: "Teams",
          dispName: "Teams",
          classid: 33,
          parentid: 93,
          level: 1,
          aclid: null,
        },
        {
          menuid: 66,
          name: "Role",
          dispName: "Role",
          classid: 34,
          parentid: 64,
          level: 1,
          aclid: null,
        },
        {
          menuid: 67,
          name: "Staff",
          dispName: "Staff",
          classid: 35,
          parentid: 64,
          level: 1,
          aclid: null,
        },
        {
          menuid: 68,
          name: "System Configuration",
          dispName: "System Configuration",
          classid: 36,
          parentid: 64,
          level: 1,
          aclid: null,
        },
        {
          menuid: 69,
          name: "OTP",
          dispName: "OTP",
          classid: 45,
          parentid: 39,
          level: 1,
          aclid: null,
        },
        {
          menuid: 70,
          name: "MVNO",
          dispName: "MVNO",
          classid: 30,
          parentid: 47,
          level: 1,
          aclid: null,
        },
        {
          menuid: 71,
          name: "IPPOOL",
          dispName: "IPPOOL",
          classid: 46,
          parentid: 45,
          level: 1,
          aclid: null,
        },
        {
          menuid: 72,
          name: "Business Unit",
          dispName: "Business Unit",
          classid: 47,
          parentid: 1,
          level: 1,
          aclid: null,
        },
        {
          menuid: 73,
          name: "Bank Management",
          dispName: "Bank Management",
          classid: 48,
          parentid: 1,
          level: 1,
          aclid: null,
        },
        {
          menuid: 74,
          name: "Branch Management",
          dispName: "Branch Management",
          classid: 49,
          parentid: 1,
          level: 1,
          aclid: null,
        },
        {
          menuid: 75,
          name: "Time Base Policy",
          dispName: "Time Base Policy",
          classid: 50,
          parentid: 14,
          level: 1,
          aclid: null,
        },
        {
          menuid: 76,
          name: "Plan Group",
          dispName: "Plan Group",
          classid: 51,
          parentid: 14,
          level: 1,
          aclid: null,
        },
        {
          menuid: 77,
          name: "Special Plan Mappping",
          dispName: "Special Plan Mappping",
          classid: 52,
          parentid: 14,
          level: 1,
          aclid: null,
        },
        {
          menuid: 78,
          name: "Manage Balance",
          dispName: "Manage Balance",
          classid: 53,
          parentid: 12,
          level: 1,
          aclid: null,
        },
        {
          menuid: 79,
          name: "Sub Reason Category",
          dispName: "Sub Reason Category",
          classid: 54,
          parentid: 33,
          level: 1,
          aclid: null,
        },
        {
          menuid: 80,
          name: "Inventory Management",
          dispName: "Inventory Management",
          classid: null,
          parentid: null,
          level: 0,
          aclid: null,
        },
        {
          menuid: 81,
          name: "Product Management",
          dispName: "Product Management",
          classid: 55,
          parentid: 80,
          level: 1,
          aclid: null,
        },
        {
          menuid: 82,
          name: "WareHouse Management",
          dispName: "WareHouse Management",
          classid: 56,
          parentid: 80,
          level: 1,
          aclid: null,
        },
        {
          menuid: 83,
          name: "Inward",
          dispName: "Inward",
          classid: 57,
          parentid: 80,
          level: 1,
          aclid: null,
        },
        {
          menuid: 84,
          name: "Outward",
          dispName: "Outward",
          classid: 58,
          parentid: 80,
          level: 1,
          aclid: null,
        },
        {
          menuid: 85,
          name: "TicketTatMatrix",
          dispName: "TicketTatMatrix",
          classid: 59,
          parentid: 33,
          level: 1,
          aclid: null,
        },
        {
          menuid: 86,
          name: "LeasedLineCustomers",
          dispName: "LeasedLineCustomers",
          classid: 60,
          parentid: 8,
          level: 1,
          aclid: null,
        },
        {
          menuid: 87,
          name: "TicketReasonCategory",
          dispName: "TicketReasonCategory",
          classid: 61,
          parentid: 33,
          level: 1,
          aclid: null,
        },
        {
          menuid: 88,
          name: "DunningRule",
          dispName: "DunningRule",
          classid: 62,
          parentid: 37,
          level: 1,
          aclid: null,
        },
        {
          menuid: 89,
          name: "ProductCategory",
          dispName: "ProductCategory",
          classid: 63,
          parentid: 80,
          level: 1,
          aclid: null,
        },
        {
          menuid: 133,
          name: "VENDOR",
          dispName: "VENDOR",
          classid: 95,
          parentid: 80,
          level: 1,
          aclid: null,
        },
        {
          menuid: 90,
          name: "PopManagement",
          dispName: "PopManagement",
          classid: 64,
          parentid: 80,
          level: 1,
          aclid: null,
        },
        {
          menuid: 91,
          name: "ExternalItemManagement",
          dispName: "ExternalItemManagement",
          classid: 65,
          parentid: 80,
          level: 1,
          aclid: null,
        },
        {
          menuid: 92,
          name: "BulkConsumption",
          dispName: "BulkConsumption",
          classid: 66,
          parentid: 80,
          level: 1,
          aclid: null,
        },
        {
          menuid: 93,
          name: "WorkFlow Management",
          dispName: "WorkFlow Management",
          classid: null,
          parentid: null,
          level: 0,
          aclid: null,
        },
        {
          menuid: 94,
          name: "Matrix",
          dispName: "Matrix",
          classid: 67,
          parentid: 93,
          level: 1,
          aclid: null,
        },
        {
          menuid: 95,
          name: "Hierarchy",
          dispName: "Hierarchy",
          classid: 68,
          parentid: 93,
          level: 1,
          aclid: null,
        },
        {
          menuid: 96,
          name: "ReportProblem",
          dispName: "ReportProblem",
          classid: 69,
          parentid: 62,
          level: 1,
          aclid: null,
        },
        {
          menuid: 97,
          name: "Sales CRM",
          dispName: "Sales CRM",
          classid: null,
          parentid: null,
          level: 0,
          aclid: null,
        },
        {
          menuid: 98,
          name: "Lead Source",
          dispName: "Lead Source",
          classid: 70,
          parentid: 97,
          level: 1,
          aclid: null,
        },
        {
          menuid: 99,
          name: "Lead Master",
          dispName: "Lead Master",
          classid: 71,
          parentid: 97,
          level: 1,
          aclid: null,
        },
        {
          menuid: 100,
          name: "Reject Reason",
          dispName: "Reject Reason",
          classid: 72,
          parentid: 97,
          level: 1,
          aclid: null,
        },
        {
          menuid: 101,
          name: "Credit Notes",
          dispName: "Credit Notes",
          classid: null,
          parentid: null,
          level: 0,
          aclid: null,
        },
        {
          menuid: 102,
          name: "Search Credit Note",
          dispName: "Search Credit Note",
          classid: 21,
          parentid: 101,
          level: 1,
          aclid: null,
        },
        {
          menuid: 107,
          name: "Generate Credit Note",
          dispName: "Generate Credit Note",
          classid: 21,
          parentid: 101,
          level: 1,
          aclid: null,
        },
        {
          menuid: 108,
          name: "Assigned Inventories",
          dispName: "Assigned Inventories",
          classid: 73,
          parentid: 80,
          level: 1,
          aclid: null,
        },
        {
          menuid: 109,
          name: "Invoice System",
          dispName: "Invoice System",
          classid: null,
          parentid: null,
          level: 0,
          aclid: null,
        },
        {
          menuid: 110,
          name: "Bill Template",
          dispName: "Bill Template",
          classid: 74,
          parentid: 109,
          level: 1,
          aclid: null,
        },
        {
          menuid: 111,
          name: "Postpaid Bill Runs",
          dispName: "Postpaid Bill Runs",
          classid: null,
          parentid: 109,
          level: 1,
          aclid: null,
        },
        {
          menuid: 112,
          name: "My Profile",
          dispName: "My Profile",
          classid: 35,
          parentid: 64,
          level: 1,
          aclid: null,
        },
        {
          menuid: 113,
          name: "Organization Profile",
          dispName: "Organization Profile",
          classid: 7,
          parentid: 64,
          level: 1,
          aclid: null,
        },
        {
          menuid: 114,
          name: "Prepaid Bill Runs",
          dispName: "Prepaid Bill Runs",
          classid: null,
          parentid: 109,
          level: 1,
          aclid: null,
        },
        {
          menuid: 115,
          name: "Invoice Master",
          dispName: "Invoice Master",
          classid: 18,
          parentid: 114,
          level: 2,
          aclid: null,
        },
        {
          menuid: 116,
          name: "Postpaid Trail Bill Runs",
          dispName: "Postpaid Trail Bill Runs",
          classid: null,
          parentid: 109,
          level: 1,
          aclid: null,
        },
        {
          menuid: 117,
          name: "Network Map",
          dispName: "Network Map",
          classid: 80,
          parentid: 45,
          level: 1,
          aclid: null,
        },
        {
          menuid: 118,
          name: "Revenue Report",
          dispName: "Revenue Report",
          classid: 81,
          parentid: 109,
          level: 1,
          aclid: null,
        },
        {
          menuid: 119,
          name: "Template Management",
          dispName: "Template Management",
          classid: 26,
          parentid: 40,
          level: 1,
          aclid: null,
        },
        {
          menuid: 128,
          name: "DTV Management",
          dispName: "DTV Management",
          classid: null,
          parentid: null,
          level: 1,
          aclid: null,
        },
        {
          menuid: 129,
          name: "CAS Management",
          dispName: "CAS Management",
          classid: 91,
          parentid: 128,
          level: 1,
          aclid: null,
        },
        {
          menuid: 130,
          name: "Sector Management",
          dispName: "Sector Management",
          classid: 92,
          parentid: 128,
          level: 1,
          aclid: null,
        },
        {
          menuid: 131,
          name: "Vendor Management",
          dispName: "Vendor Management",
          classid: 93,
          parentid: 80,
          level: 1,
          aclid: null,
        },
        {
          menuid: 132,
          name: "Reject Reason",
          dispName: "Reject Reason",
          classid: 7,
          parentid: 10,
          level: 1,
          aclid: null,
        },
        {
          menuid: 140,
          name: "VoucherConfiguration",
          dispName: "VoucherConfiguration",
          classid: 102,
          parentid: 14,
          level: 1,
          aclid: null,
        },
        {
          menuid: 141,
          name: "Department Management",
          dispName: "Department Management",
          classid: 50,
          parentid: 1,
          level: 1,
          aclid: null,
        },
      ];
    }
  }

  //   public menuItems: any = [
  //     {
  //       id: 1,
  //       name: "Masters",
  //       subClassess: [
  //         {
  //           id: 1,
  //           name: "Country",
  //         },
  //         {
  //           id: 2,
  //           name: "State",
  //         },
  //         {
  //           id: 3,
  //           name: "City",
  //         },
  //         {
  //           id: 4,
  //           name: "Pincode",
  //         },
  //         {
  //           id: 5,
  //           name: "Area",
  //         },
  //         {
  //           id: 6,
  //           name: "Service Area",
  //         },
  //         {
  //           id: 47,
  //           name: "BusinessUnit",
  //         },
  //         {
  //           id: 48,
  //           name: "BankManagement",
  //         },
  //         {
  //           id: 49,
  //           name: "Branch",
  //         },
  //       ],
  //     },
  //     {
  //       id: 8,
  //       name: "Customer",
  //       subClassess: [
  //         {
  //           id: 7,
  //           name: "Postpaid Customer",
  //         },
  //         {
  //           id: 10,
  //           name: "Prepaid Customer",
  //         },
  //         {
  //           id: 11,
  //           name: "Customer CAF",
  //         },
  //         {
  //           id: 60,
  //           name: "Leased Line Customers",
  //         },
  //       ],
  //     },
  //     {
  //       id: 12,
  //       name: "Partner",
  //       subClassess: [
  //         {
  //           id: 8,
  //           name: "Partner",
  //         },
  //         {
  //           id: 15,
  //           name: "Plan Bundle",
  //         },
  //         {
  //           id: 53,
  //           name: "PartnerPayment",
  //         },
  //       ],
  //     },
  //     {
  //       id: 14,
  //       name: "Product",
  //       subClassess: [
  //         {
  //           id: 9,
  //           name: "Service",
  //         },
  //         {
  //           id: 10,
  //           name: "Tax",
  //         },
  //         {
  //           id: 11,
  //           name: "Charge",
  //         },
  //         {
  //           id: 12,
  //           name: "Discount",
  //         },
  //         {
  //           id: 13,
  //           name: "Qos Policy",
  //         },
  //         {
  //           id: 14,
  //           name: "Plan",
  //         },
  //         {
  //           id: 15,
  //           name: "Plan Bundle",
  //         },
  //         {
  //           id: 50,
  //           name: "TimeBasePolicy",
  //         },
  //         {
  //           id: 51,
  //           name: "PlanGroup",
  //         },
  //         {
  //           id: 52,
  //           name: "CustSpecialPlanMappping",
  //         },
  //       ],
  //     },
  //     {
  //       id: 22,
  //       name: "Billing",
  //       subClassess: [
  //         {
  //           id: 16,
  //           name: "Bill Template",
  //         },
  //         {
  //           id: 17,
  //           name: "Bill Run",
  //           subChildClassess: [
  //             {
  //               id: 17,
  //               name: "Bill Run Master",
  //             },
  //             {
  //               id: 18,
  //               name: "Invoice Master",
  //             },
  //           ],
  //         },
  //         {
  //           id: 27,
  //           name: "Trial Bill Run",
  //           subChildClassess: [
  //             {
  //               id: 19,
  //               name: "Trial Bill Run Master",
  //             },
  //             {
  //               id: 20,
  //               name: "Trial Invoice Master",
  //             },
  //           ],
  //         },
  //       ],
  //     },
  //     {
  //       id: 30,
  //       name: "Payment",
  //       subClassess: [
  //         {
  //           id: 21,
  //           name: "Record Payment",
  //         },
  //         {
  //           id: 21,
  //           name: "Search Payment",
  //         },
  //       ],
  //     },
  //     {
  //       id: 33,
  //       name: "Ticket",
  //       subClassess: [
  //         {
  //           id: 59,
  //           name: "TAT For Ticket",
  //         },
  //         {
  //           id: 22,
  //           name: "Resolution Master",
  //         },
  //         {
  //           id: 23,
  //           name: "Ticket Reason",
  //         },
  //         {
  //           id: 24,
  //           name: "Ticket",
  //         },
  //         {
  //           id: 54,
  //           name: "TicketReasonSubCategory",
  //         },
  //       ],
  //     },
  //     {
  //       id: 37,
  //       name: "Dunning",
  //       subClassess: [
  //         {
  //           id: 25,
  //           name: "Dunning Rules",
  //         },
  //       ],
  //     },
  //     {
  //       id: 39,
  //       name: "Notification",
  //       subClassess: [
  //         {
  //           id: 26,
  //           name: "Template",
  //         },
  //         {
  //           id: 27,
  //           name: "Email Configuration",
  //         },
  //         {
  //           id: 28,
  //           name: "SMS Configuration",
  //         },
  //         {
  //           id: 43,
  //           name: "Email",
  //         },
  //         {
  //           id: 44,
  //           name: "SMS",
  //         },
  //         {
  //           id: 45,
  //           name: "OTP",
  //         },
  //       ],
  //     },
  //     {
  //       id: 45,
  //       name: "Network",
  //       subClassess: [
  //         {
  //           id: 29,
  //           name: "Network Device",
  //         },
  //         {
  //           id: 46,
  //           name: "IPPOOL",
  //         },
  //       ],
  //     },
  //     {
  //       id: 47,
  //       name: "MVNO",
  //     },
  //     {
  //       id: 48,
  //       name: "AAA",
  //       subClassess: [
  //         {
  //           id: 38,
  //           name: "Radius Group",
  //         },
  //         {
  //           id: 37,
  //           name: "Radius Client",
  //         },
  //         {
  //           id: 38,
  //           name: "Radius Customer",
  //         },
  //         {
  //           id: 39,
  //           name: "CDRs",
  //         },
  //         {
  //           id: 40,
  //           name: "Live Users",
  //         },
  //         {
  //           id: 54,
  //           name: "Proxy Configuration",
  //         },
  //         {
  //           id: 41,
  //           name: "Dictionary",
  //         },
  //         {
  //           id: 42,
  //           name: "Authentication Audit",
  //         },
  //         {
  //           id: 43,
  //           name: "CoA/DM Profile",
  //         },
  //         {
  //           id: 31,
  //           name: "Radius Profile",
  //         },
  //         {
  //           id: 43,
  //           name: "Device Management",
  //         },
  //         {
  //           id: 44,
  //           name: "DB Mapping Master",
  //         },
  //         {
  //           id: 61,
  //           name: "Template Management",
  //         },
  //       ],
  //     },
  //     {
  //       id: 62,
  //       name: "Audit",
  //       subClassess: [
  //         {
  //           id: 32,
  //           name: "Audit Log",
  //         },
  //       ],
  //     },
  //     {
  //       id: 64,
  //       name: "Settings",
  //       subClassess: [
  //         {
  //           id: 33,
  //           name: "Teams",
  //         },
  //         {
  //           id: 34,
  //           name: "Role",
  //         },
  //         {
  //           id: 35,
  //           name: "Staff",
  //         },
  //         {
  //           id: 36,
  //           name: "System Configuration",
  //         },
  //       ],
  //     },
  //     {
  //       id: 80,
  //       name: "Inventory Management",
  //       subClassess: [
  //         {
  //           id: 55,
  //           name: "Product Management",
  //         },
  //         {
  //           id: 56,
  //           name: "Warehourse Management",
  //         },
  //         {
  //           id: 57,
  //           name: "Inwards",
  //         },
  //         {
  //           id: 58,
  //           name: "Outwards",
  //         },
  //       ],
  //     },
  //     {
  //       id: 85,
  //       name: "Lead",
  //       subClassess: [
  //         {
  //           id: 75,
  //           name: "Lead Source Master",
  //         },
  //         {
  //           id: 76,
  //           name: "Lead Management",
  //         },
  //         {
  //           id: 77,
  //           name: "Rejected Reason Master",
  //         },
  //       ],
  //     },
  //   ];

  public getMenuId(menuName) {
    let filterPersmissionList = this.menuItems.filter(menu => menu.name === menuName);
    if (filterPersmissionList && filterPersmissionList?.length !== 0) {
      return filterPersmissionList[0].menuid;
    }
  }

  public getSubMenuId(menuName, subMenuName) {
    let filterPersmissionList = this.menuItems.filter(menu => menu.name === subMenuName);

    if (filterPersmissionList && filterPersmissionList?.length !== 0) {
      //   let submenuList = filterPersmissionList[0].subClassess.filter(
      //     subMenu => subMenu.name === subMenuName
      //   );
      return filterPersmissionList[0].menuid;
    }
  }

  public getChildSubMenuId(menuName, subMenuName, childSubMenuName) {
    let filterPersmissionList = this.menuItems.filter(menu => menu.name === childSubMenuName);
    // let list = filterPersmissionList.filter(item => item.permits.includes(constantVar));
    if (filterPersmissionList && filterPersmissionList?.length !== 0) {
      return filterPersmissionList[0].menuid;
    }

    // let submenuList = filterPersmissionList[0].subClassess.filter(
    //   subMenu => subMenu.name === subMenuName
    // );
    // if (submenuList.length !== 0) {
    //   if (submenuList[0].subChildClassess.length !== 0) {
    //     let childSubmenuList = submenuList[0].subChildClassess.filter(
    //       childSubMenu => childSubMenu.name === childSubMenuName
    //     );
    //     if (childSubmenuList.length !== 0) {
    //     }
    //   }
    // }
  }
}
