server {
    listen 443 ssl;
    server_name example.com;

    ssl_certificate /etc/certi/domain.crt;
    ssl_certificate_key /etc/certi/domain.key;

    location / {
        root /usr/share/nginx/html;
        index index.html;
        try_files $uri $uri/ /index.html;
    }
    location = /assets/env.js {
    # Deny access unless the X-Script-Tag-Request header is present and set to "true"
    if ($http_x_script_tag_request != "true") {
        return 403;
    }
    # Allow access if the header is present and set to "true"
    root /usr/share/nginx/html;
  }
}
